version: '3'

services:
  rabbitmq:
    image: "rabbitmq:3-management-alpine"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  apartments:
    build: ./apartments
    ports:
      - "5001:5001"
    depends_on:
      - rabbitmq
    command: sh -c "sleep 30s ; python3 ./app.py" #perdorim sh -c "COMMANDS ; GO ; HERE" meqe kemi disa komanda