# Use the official Python Alpine image as the base image
FROM python:3.9-alpine

# Set the working directory within the container
WORKDIR /PROJECT

RUN pip install --upgrade pip

# Copy only the necessary files (e.g., your Python script and requirements.txt)
COPY requirements.txt app.py apartments.db ./

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Update package index and install curl
# RUN apk update && apk add --no-cache curl

# Expose port 5000
EXPOSE 5001

# RUN apt-get -y update

# RUN apt-get -y install curl

# Specify the command to run your Python application
CMD ["python3", "app.py"]

# RUN sh -c "apt-get -y update; apt-get -y install curl"
